#### PyTorch Neural Network Training Pipeline
In the current notebook, we will take a real dataset and create a neural network for training it to mimic the training pipeline.
##### Current Notebook
1. We will build a simple neural Network 
2. Train it on a real world dataset
3. Will mimic the PyTorch workflow 
4. Will have a lot of manual elements
5. End result is not important

In [58]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [59]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [60]:
df.shape

(569, 33)

In [61]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True) # Inplace means : The chage happens in the original dataset

In [62]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

##### Train Test Split

In [63]:
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

##### Scaler

In [64]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [65]:
X_train

array([[ 0.86499242, -0.69716692,  1.00051776, ...,  2.13256314,
         1.85019416,  1.16303243],
       [-0.81806441, -1.06880441, -0.85181036, ..., -1.49933124,
        -0.14074998, -0.5576974 ],
       [ 0.23920389, -0.15347504,  0.24663433, ..., -0.47253208,
        -0.08186514,  0.4187571 ],
       ...,
       [ 1.7193795 ,  2.02129248,  1.63152151, ...,  0.72753372,
        -0.52748014, -0.98137016],
       [-0.30371767, -1.28444591, -0.38146348, ..., -1.21512518,
        -1.26751932, -1.01229122],
       [ 0.05061009, -0.60081646, -0.06637674, ..., -1.24545065,
        -0.7089091 , -1.26182959]])

In [66]:
X_test

array([[ 1.03929882,  1.97082319,  1.05448519, ...,  1.24870515,
         0.10911271,  0.34118322],
       [-0.68947772, -0.07547705, -0.72934582, ..., -0.8784972 ,
         0.92872601, -0.80723577],
       [-0.50088392, -0.20623839, -0.53506308, ..., -0.46689368,
         0.12661902, -0.68409401],
       ...,
       [-0.70948009,  2.25987457, -0.70692858, ..., -0.71178329,
        -0.03093771, -0.6651074 ],
       [-0.68662024, -0.51593629, -0.71481612, ..., -0.07860572,
        -0.52748014, -0.73183179],
       [ 1.44506124,  1.22984228,  1.6813376 , ...,  0.93935486,
         0.43377507,  0.96774153]])

In [67]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)


In [68]:
X_train

array([[ 0.86499242, -0.69716692,  1.00051776, ...,  2.13256314,
         1.85019416,  1.16303243],
       [-0.81806441, -1.06880441, -0.85181036, ..., -1.49933124,
        -0.14074998, -0.5576974 ],
       [ 0.23920389, -0.15347504,  0.24663433, ..., -0.47253208,
        -0.08186514,  0.4187571 ],
       ...,
       [ 1.7193795 ,  2.02129248,  1.63152151, ...,  0.72753372,
        -0.52748014, -0.98137016],
       [-0.30371767, -1.28444591, -0.38146348, ..., -1.21512518,
        -1.26751932, -1.01229122],
       [ 0.05061009, -0.60081646, -0.06637674, ..., -1.24545065,
        -0.7089091 , -1.26182959]])

In [69]:
Y_train # We will encode them as the model will not understand the text here

25     M
333    B
147    B
411    B
297    M
      ..
196    M
54     M
565    M
309    B
270    B
Name: diagnosis, Length: 455, dtype: object

##### Label Encoding

In [70]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(Y_train)
y_test = encoder.fit_transform(Y_test)

In [71]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,

In [72]:
y_test

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1])

##### Numy arraya to PyTorch Tensors

In [73]:
x_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [74]:
x_train_tensor

tensor([[ 0.8650, -0.6972,  1.0005,  ...,  2.1326,  1.8502,  1.1630],
        [-0.8181, -1.0688, -0.8518,  ..., -1.4993, -0.1407, -0.5577],
        [ 0.2392, -0.1535,  0.2466,  ..., -0.4725, -0.0819,  0.4188],
        ...,
        [ 1.7194,  2.0213,  1.6315,  ...,  0.7275, -0.5275, -0.9814],
        [-0.3037, -1.2844, -0.3815,  ..., -1.2151, -1.2675, -1.0123],
        [ 0.0506, -0.6008, -0.0664,  ..., -1.2455, -0.7089, -1.2618]],
       dtype=torch.float64)

In [75]:
x_train_tensor.shape

torch.Size([455, 30])

##### My Simple Neural Network

In [89]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


##### Important Parameters

In [94]:
learning_rate = 0.01 
epochs = 50

##### Training Pipeline

In [79]:
# Forward pass
# Loss Calculate
# Backward pass
# Parameters update : We do all the steps in a lopp as per our number of epochs

In [95]:
# Create the model
model = MySimpleNN(x_train_tensor)

# Define loop
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(x_train_tensor)

    # Loss Calculation
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward pass: compute gradients
    loss.backward()  # <-- this line was missing

    # Parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero Gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Print loss in each epoch
    print(f"Epoch : {epoch + 1}, Loss: {loss.item()}")


Epoch : 1, Loss: 4.022198512038406
Epoch : 2, Loss: 4.01146208630455
Epoch : 3, Loss: 4.0006392083590026
Epoch : 4, Loss: 3.9898248819826025
Epoch : 5, Loss: 3.978992578330634
Epoch : 6, Loss: 3.9680236222818928
Epoch : 7, Loss: 3.956998162457519
Epoch : 8, Loss: 3.945794522164143
Epoch : 9, Loss: 3.9344606114123013
Epoch : 10, Loss: 3.9231039538395427
Epoch : 11, Loss: 3.9116141411359364
Epoch : 12, Loss: 3.9001338092653928
Epoch : 13, Loss: 3.8886630400615565
Epoch : 14, Loss: 3.877201398677053
Epoch : 15, Loss: 3.86557151651487
Epoch : 16, Loss: 3.853924769015754
Epoch : 17, Loss: 3.8421735803559134
Epoch : 18, Loss: 3.830232323009048
Epoch : 19, Loss: 3.8181359659004963
Epoch : 20, Loss: 3.8059225042187705
Epoch : 21, Loss: 3.793716392251517
Epoch : 22, Loss: 3.7813558809079755
Epoch : 23, Loss: 3.7689525605123326
Epoch : 24, Loss: 3.75635563936467
Epoch : 25, Loss: 3.743584242483602
Epoch : 26, Loss: 3.730693881510757
Epoch : 27, Loss: 3.717736596307292
Epoch : 28, Loss: 3.7045391

In [98]:
# Evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5146198868751526
