##### DataLoader and Dataset in PyTorch

Dataset and DataLoader are core abstractions in PyTorch that decouple how you define. your data from how efficiantly iterate over it in training loops.

In [84]:
from sklearn.datasets import make_classification
import torch

In [85]:
# Step 1 : Create a synthetic classification dataset using sklearn

X, y = make_classification(
    n_samples = 10, # Number of Samples
    n_features = 2, # Number of features
    n_informative = 2, # Number of informative features
    n_redundant= 0,  # Number of redundant features
    n_classes = 2,  # Number of classes
    random_state = 42 # For reproducibility
)

In [86]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [87]:
X.shape

(10, 2)

In [88]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [89]:
y.shape

(10,)

In [90]:
# Convert the numpy arrays to tensors 

X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [91]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [92]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [93]:
from torch.utils.data import Dataset, DataLoader

In [94]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [95]:
dataset = CustomDataset(X, y)

In [96]:
len(dataset)

10

In [97]:
dataset[0] # we can access any element from here

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [98]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [99]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("_"*50)

tensor([[-1.1402, -0.8388],
        [-1.9629, -0.9923]])
tensor([0., 0.])
__________________________________________________
tensor([[-0.9382, -0.5430],
        [ 1.7273, -1.1858]])
tensor([1., 1.])
__________________________________________________
tensor([[-0.5872, -1.9717],
        [ 1.8997,  0.8344]])
tensor([0., 1.])
__________________________________________________
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0., 0.])
__________________________________________________
tensor([[ 1.7774,  1.5116],
        [ 1.0683, -0.9701]])
tensor([1., 1.])
__________________________________________________


##### New Example

In [100]:
import numpy as np
import pandas as pd
import torch 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [101]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [102]:
df.shape

(569, 33)

In [103]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

##### Train Test Split

In [104]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

##### Scaling

In [105]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [106]:
X_train

array([[-0.61485315,  2.09416583, -0.63900256, ..., -0.67737258,
        -0.72334521, -0.10488072],
       [-1.12669256, -1.03694889, -1.08995701, ..., -1.15270671,
        -0.74384291,  0.06401984],
       [ 0.28233662, -0.02721071,  0.23517499, ..., -0.03921854,
        -0.9835083 , -0.81725041],
       ...,
       [ 1.56193514,  0.99873886,  1.59358462, ...,  0.65456302,
         0.02245564, -0.4380859 ],
       [ 0.97949719,  1.475817  ,  0.97069578, ..., -0.07203254,
        -2.05411882, -0.89538128],
       [ 0.16173078, -0.91420549,  0.1716062 , ...,  0.39361365,
         0.38668396,  0.05540246]])

In [107]:
y_train

452    B
345    B
514    M
40     M
194    M
      ..
466    B
388    B
244    M
213    M
89     B
Name: diagnosis, Length: 455, dtype: object

##### Label Encoding

In [108]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [109]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,

##### Numpy to PyTorch Tensors

In [110]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [111]:
X_train_tensor.shape

torch.Size([455, 30])

In [112]:
y_train_tensor.shape

torch.Size([455])

In [113]:
from torch.utils.data import DataLoader, Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels


    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


In [114]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [115]:
train_dataset[10]

(tensor([-0.3648,  0.5054, -0.3890, -0.4008, -1.5403, -0.4184, -0.3504, -0.8082,
         -0.8582, -0.2478,  0.3336,  1.0667, -0.1582,  0.0240, -0.3360,  1.1303,
          0.6216,  0.2429,  0.7484,  1.4015, -0.3891,  0.2478, -0.4719, -0.4142,
         -1.7354, -0.3941, -0.4216, -0.9141, -0.6587, -0.1296],
        dtype=torch.float64),
 tensor(0))

In [116]:
test_dataset[10]

(tensor([-0.6066,  0.4399, -0.5858, -0.6038, -1.9352,  0.0785, -0.0076, -0.5720,
         -1.7037,  0.6732, -0.5525,  0.5710, -0.4670, -0.5024, -0.1077,  1.6958,
          1.4968,  0.6697,  0.3561,  2.6689, -0.6801,  0.2865, -0.6646, -0.6248,
         -1.4838,  0.4110,  0.1846, -0.3819, -1.0492,  0.7289],
        dtype=torch.float64),
 tensor(0))

In [117]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

##### Defining Model

In [118]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

##### Important Parameters

In [119]:
learning_rate = 0.1
epochs = 25

In [120]:
# Create the model
model = MySimpleNN(X_train_tensor.shape[1])

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define loss function
loss_function = nn.BCELoss()


##### Training Pipeline

In [121]:
# Define Loop
for epoch in range(epochs):

    for batch_features, batch_labels in train_loader:
        # Forward pass
        y_pred = model(batch_features)

        # Loss Calculate
        loss = loss_function(y_pred, batch_labels.view(-1, 1))

        # Clear Gradients
        optimizer.zero_grad()

        # Backward pass
        loss.backward()

        # Parameters update
        optimizer.step()

RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float