##### DataLoader and Dataset in PyTorch

Dataset and DataLoader are core abstractions in PyTorch that decouple how you define. your data from how efficiantly iterate over it in training loops.

In [161]:
from sklearn.datasets import make_classification
import torch

In [162]:
# Step 1 : Create a synthetic classification dataset using sklearn

X, y = make_classification(
    n_samples = 10, # Number of Samples
    n_features = 2, # Number of features
    n_informative = 2, # Number of informative features
    n_redundant= 0,  # Number of redundant features
    n_classes = 2,  # Number of classes
    random_state = 42 # For reproducibility
)

In [163]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [164]:
X.shape

(10, 2)

In [165]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [166]:
y.shape

(10,)

In [167]:
# Convert the numpy arrays to tensors 

X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [168]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [169]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [170]:
from torch.utils.data import Dataset, DataLoader

In [171]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [172]:
dataset = CustomDataset(X, y)

In [173]:
len(dataset)

10

In [174]:
dataset[0] # we can access any element from here

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [175]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [176]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("_"*50)

tensor([[-0.7206, -0.9606],
        [ 1.7273, -1.1858]])
tensor([0., 1.])
__________________________________________________
tensor([[-0.9382, -0.5430],
        [-1.9629, -0.9923]])
tensor([1., 0.])
__________________________________________________
tensor([[ 1.8997,  0.8344],
        [ 1.0683, -0.9701]])
tensor([1., 1.])
__________________________________________________
tensor([[-2.8954,  1.9769],
        [-0.5872, -1.9717]])
tensor([0., 0.])
__________________________________________________
tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]])
tensor([0., 1.])
__________________________________________________


##### New Example

In [177]:
import numpy as np
import pandas as pd
import torch 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [178]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [179]:
df.shape

(569, 33)

In [180]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

##### Train Test Split

In [181]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

##### Scaling

In [182]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [183]:
X_train

array([[ 0.09992924,  0.79473541,  0.14706676, ..., -0.10986326,
        -1.03756279, -0.23322706],
       [-0.78714882, -0.88016841, -0.80175578, ..., -0.50072131,
        -0.37269956, -0.90655073],
       [ 1.94426558,  0.87744671,  1.80679447, ...,  1.26284722,
        -0.1404746 , -0.49299196],
       ...,
       [-0.84610021,  0.14683023, -0.84730577, ..., -1.48075155,
         0.60709889, -1.03860694],
       [ 0.01571297, -0.55162074, -0.10061131, ..., -1.28167817,
        -0.71944641, -1.25707031],
       [ 1.92461511,  1.68847695,  2.03047745, ...,  2.62037284,
         1.8891079 ,  2.39485468]])

In [184]:
y_train

558    B
137    B
23     M
482    B
533    M
      ..
407    B
291    B
332    B
270    B
181    M
Name: diagnosis, Length: 455, dtype: object

##### Label Encoding

In [185]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [186]:
y_train

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,

##### Numpy to PyTorch Tensors

In [187]:
X_train_tensor = torch.from_numpy(X_train).to(torch.float32)
X_test_tensor = torch.from_numpy(X_test).to(torch.float32)
y_train_tensor = torch.from_numpy(y_train).to(torch.float32)
y_test_tensor = torch.from_numpy(y_test).to(torch.float32)

In [188]:
X_train_tensor.shape

torch.Size([455, 30])

In [189]:
y_train_tensor.shape

torch.Size([455])

In [190]:
from torch.utils.data import DataLoader, Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels


    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


In [191]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [192]:
train_dataset[10]

(tensor([-0.3520,  0.0297, -0.3357, -0.4258, -0.1045,  0.0972, -0.2633, -0.5483,
         -0.2332,  0.3254, -0.5340, -1.2000, -0.2348, -0.4874, -0.4483,  0.3504,
          0.3943, -0.3676,  0.7944,  0.2529, -0.4102, -0.5693, -0.2706, -0.4634,
         -0.1903,  0.4144,  0.3178, -0.2909,  1.0906,  0.3983]),
 tensor(0.))

In [193]:
test_dataset[10]

(tensor([ 4.1359,  1.6526,  4.3210,  5.5574,  1.2162,  2.2518,  3.9685,  3.7519,
          1.2415, -0.9267,  7.4351,  0.0570,  7.8285,  8.8000,  0.3414,  1.9539,
          1.5024,  2.7301, -0.4542,  0.5283,  4.4598,  0.9082,  4.7364,  5.9204,
          0.3120,  1.3018,  2.0535,  2.5285, -0.3871, -0.4943]),
 tensor(1.))

In [194]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

##### Defining Model

In [195]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

##### Important Parameters

In [196]:
learning_rate = 0.1
epochs = 25

In [197]:
# Create the model
model = MySimpleNN(X_train_tensor.shape[1])

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define loss function
loss_function = nn.BCELoss()


##### Training Pipeline

In [198]:
# Define Loop
for epoch in range(epochs):

    for batch_features, batch_labels in train_loader:
        # Forward pass
        y_pred = model(batch_features)

        # Loss Calculate
        loss = loss_function(y_pred, batch_labels.view(-1, 1))

        # Clear Gradients
        optimizer.zero_grad()

        # Backward pass
        loss.backward()

        # Parameters update
        optimizer.step()