#### RNN

In [5]:
import pandas as pd

df = pd.read_csv('/Users/mekalathuruchenchaiah/Desktop/Programming/Deep Learing-PyTorch/data/100_Unique_QA_Dataset.csv')

In [6]:
df.head()

question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [7]:
# Tokenize 
def tokenize(text):
    text = text.lower()
    text = text.replace('?', '')
    text = text.replace("'", "")
    return text.split()

In [8]:
tokenize("What is the capital of France?")

['what', 'is', 'the', 'capital', 'of', 'france']

In [9]:
# Vocabulary Building
vocab = {'<UNK>' : 0}



In [10]:
len(vocab)

1

In [11]:
def build_vocab(row):
    tokenized_question = tokenize(row['question']) 
    tokenized_answer = tokenize(row['answer'])
    merged_tokens = tokenized_question + tokenized_answer
    # ['what', 'is', 'the', 'capital', 'of', 'france']
    for token in merged_tokens:
        if token not in vocab:
            vocab[token] = len(vocab)

In [12]:
df.apply(build_vocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [13]:
len(vocab)

324

In [14]:
# Convert words to numarical indices 

def text_to_indices(text, vocab):
    indexed_text = []
    for token in tokenize(text):
        if token in vocab:
            indexed_text.append(vocab[token])
        else:
            indexed_text.append(vocab['<UNK>'])
    return indexed_text

In [15]:
text_to_indices("What is campusx", vocab)

[1, 2, 0]

In [16]:
import torch 
from torch.utils.data import Dataset, DataLoader

In [17]:
class QADataset(Dataset):
    def __init__(self, df, vocab):
        self.df = df
        self.vocab = vocab

    def __len__(self):
        return self.df.shape[0]
    
    def __getitem__(self, index):
        newmarical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
        numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)
        return torch.tensor(newmarical_question), torch.tensor(numerical_answer)

In [18]:
dataset = QADataset(df, vocab)

In [19]:
print(dataset.__getitem__(0))


(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))


In [20]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [21]:
for question, answer in dataloader:
    print(question, answer[0])

tensor([[10,  2,  3, 66,  5, 67]]) tensor([68])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([72])
tensor([[ 10,  96,   3, 104, 239]]) tensor([240])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([185])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([259])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([41])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([287])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([238])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([295])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([194])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([199])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([106])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([54])
tensor([[10, 96,  3, 97]]) tensor([98])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([316])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([136])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([149])
tensor([[ 42, 26

In [22]:
import torch 
from torch.utils.data import Dataset, DataLoader

In [25]:
class QADataset(Dataset):
    def __init__(self, df, vocab):
        self.df = df
        self.vocab = vocab

    def __len__(self):
        return self.df.shape[0]
    
    def __getitem__(self, index):
        newmarical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
        numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)
        return torch.tensor(newmarical_question), torch.tensor(numerical_answer)

In [26]:
dataset = QADataset(df, vocab)

In [31]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [32]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [33]:
for question, answer in dataloader:
    print(question, answer[0])

tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([316])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([205])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([238])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([136])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([128])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([295])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([58])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([54])
tensor([[ 42, 101,   2,   3,  17]]) tensor([102])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([280])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([170])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([61])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([134])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([145])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([276])
tensor([[

In [ ]:
#### RNN Architecture and Training 

import torch 
import torch.nn as nn 

class SimpleRNN(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
        self.rnn = nn.RNN(50, 64)
        self.fc = nn.Linear(64, vocab_size)

    def forward(self, x):
        pass



