In [1]:
import torch

In [3]:
data = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 0, 9])

reshape = data.view(5, 2)

print(reshape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [0, 9]])


In [4]:
flatten = data.view(-1)
print(flatten)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 0, 9])


In [5]:
reshape.view(-1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 0, 9])

In [7]:
t1 = torch.tensor([[[1, 2],
         [3, 4]],
        [[5, 6],
         [7, 8]]])

In [8]:
t1

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [9]:
t1.shape

torch.Size([2, 2, 2])

In [10]:
t2 = t1.view(-1)

In [11]:
t2

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
t2.shape

torch.Size([8])