### Pytorch Imp Concepts


In [1]:
# Creating two random tensors and performing basic operations

import torch 

a = torch.rand(4, 3)
b = torch.rand(4, 3)

print("Tensor a:", a)
print("Tensor b:", b)

Tensor a: tensor([[0.8550, 0.8853, 0.3186],
        [0.1286, 0.8466, 0.8536],
        [0.1277, 0.4696, 0.1550],
        [0.2562, 0.0148, 0.1353]])
Tensor b: tensor([[0.2840, 0.9519, 0.4748],
        [0.8521, 0.4486, 0.8995],
        [0.5584, 0.9894, 0.4668],
        [0.8913, 0.8510, 0.5656]])


In [2]:
print(f"a={a}, \n b={b}")

a=tensor([[0.8550, 0.8853, 0.3186],
        [0.1286, 0.8466, 0.8536],
        [0.1277, 0.4696, 0.1550],
        [0.2562, 0.0148, 0.1353]]), 
 b=tensor([[0.2840, 0.9519, 0.4748],
        [0.8521, 0.4486, 0.8995],
        [0.5584, 0.9894, 0.4668],
        [0.8913, 0.8510, 0.5656]])


In [3]:
add = a + b
sub = a - b
mul = a * b

print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", mul)

Addition:
 tensor([[1.1389, 1.8372, 0.7933],
        [0.9807, 1.2952, 1.7531],
        [0.6861, 1.4590, 0.6219],
        [1.1475, 0.8658, 0.7010]])
Subtraction:
 tensor([[ 0.5710, -0.0666, -0.1562],
        [-0.7236,  0.3981, -0.0460],
        [-0.4307, -0.5198, -0.3118],
        [-0.6351, -0.8361, -0.4303]])
Multiplication:
 tensor([[0.2428, 0.8427, 0.1513],
        [0.1096, 0.3798, 0.7678],
        [0.0713, 0.4646, 0.0724],
        [0.2283, 0.0126, 0.0765]])


In [4]:
# Matrix multiplication, note the use of transpose

a_transpose = a.T
print(f"Shape -> a: {a.shape}")
print(f"Shape -> a_transpose: {a_transpose.shape}")

Shape -> a: torch.Size([4, 3])
Shape -> a_transpose: torch.Size([3, 4])


In [5]:
dot_AB = a @ b.T
print(dot_AB)

tensor([[1.2367, 1.4122, 1.5020, 1.6956],
        [1.2477, 1.2572, 1.3079, 1.3179],
        [0.5569, 0.4589, 0.6083, 0.6011],
        [0.1511, 0.3467, 0.2209, 0.3175]])


In [6]:
dot_BA = a.T @ b
print(dot_BA)

tensor([[0.6520, 1.2158, 0.7261],
        [1.2483, 1.6997, 1.4095],
        [1.0250, 0.9547, 1.0680]])


In [7]:
# Broadcasting rules in PyTorch which allow operations on tensors of different shapes

c = torch.rand(4, 1)
print(f"Tensor c:\n{c}")


Tensor c:
tensor([[0.7512],
        [0.0236],
        [0.8178],
        [0.8267]])
